Description: Downloads both the Intel and Apple Silicon versions of Joan Configurator for packaging into a Universal installer.
Identifier: com.github.jc0b.download.JoanConfigurator
MinimumVersion: '2.3'

Input:
  NAME: JoanConfigurator
  SEARCH_URL: "https://support.getjoan.com/knowledge/download-joan-configurator-for-desktop-1"

Process:
  - Processor: URLTextSearcher
    Arguments:
      re_flags:
        - IGNORECASE
      re_pattern: 'href="(https://files.joanassistant.com/JoanConfigurator2.0/.*arm64-mac.dmg)"'
      url: '%SEARCH_URL%'

  - Processor: URLDownloader
    Arguments:
      filename: '%NAME%-arm64.dmg'
      download_dir: '%RECIPE_CACHE_DIR%/downloads'
      url: '%match%'

  - Processor: URLTextSearcher
    Arguments:
      re_flags:
        - IGNORECASE
      re_pattern: 'href="(https://files.joanassistant.com/JoanConfigurator2.0/.*x64-mac.dmg)"'
      url: '%SEARCH_URL%'

  - Processor: URLDownloader
    Arguments:
      filename: '%NAME%-x86_64.dmg'
      download_dir: '%RECIPE_CACHE_DIR%/downloads'
      url: '%match%'

  - Processor: EndOfCheckPhase

  - Processor: AppDmgVersioner
    Arguments:
      dmg_path: '%RECIPE_CACHE_DIR%/downloads/%NAME%-arm64.dmg'

  - Processor: CodeSignatureVerifier
    Arguments:
      input_path: '%RECIPE_CACHE_DIR%/downloads/%NAME%-arm64.dmg/Joan configurator.app'
      requirement: identifier "com.electron.joan-configurator" and anchor apple generic and certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */ and certificate leaf[subject.OU] = Z86PF9M8GG
      deep_verification: True
      strict_verification: True

  - Processor: CodeSignatureVerifier
    Arguments:
      input_path: '%RECIPE_CACHE_DIR%/downloads/%NAME%-x86_64.dmg/Joan configurator.app'
      requirement: identifier "com.electron.joan-configurator" and anchor apple generic and certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */ and certificate leaf[subject.OU] = Z86PF9M8GG
      deep_verification: True
      strict_verification: True